### ISSUE TITLE
How about adding the 'gist.github.com/*' ?

### ISSUE THREAD

**Issue by imknown** [Nuclides/github-highlight-selected#14]
Is it the core code?

https://github.com/Nuclides/github-highlight-selected/blob/master/manifest.json#L14

**Comment by xhacker** [comment]
I’m not sure simply adding that would work. You can have a try :)

**Comment by stevennoto** [comment]
I know it's been a while since this was opened, but I figured out a way to solve this, and opened #17 for this. It should work for all gists now. Let me know if you'd like any further changes. Thanks!
