### ISSUE TITLE
Doesn't work in PRs

### ISSUE THREAD

**Issue by daguej** [Nuclides/github-highlight-selected#9]
This extension is great when looking at files, but doesn't seem to work when looking at diffs (ie in a PR or commit view).

**Comment by caesarsol** [comment]
Seems it could be generalized with a common parent Div class.

What about (https://github.com/Nuclides/github-highlight-selected/blob/master/src/highlight-selected.js#L2):
```diff
- var fileLineContainer = '.js-file-line-container';
+ var fileLineContainer = '.blob-wrapper'; 
```

**Comment by xhacker** [comment]
@caesarsol: Pushed a partial fix as per @caesarsol’s comment.

Still need a way to observe the expansion of code, and re-run `wrapTextNodes()`.

**Comment by vairix-dmacchi** [comment]
I think that this could be very helpful when you do code reviews. +1 to add it!

**Comment by pkjg** [comment]
+1
